site_name: Сайт-портфолио Alwiest

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: white

nav:
  - Главная: index.md
  - Об авторе: about/index.md
  - Лабораторные работы:
      - Лабораторная 1: labs/lab1.md